### ISSUE TITLE
Reservation Shows "&amp;" Instead of "&"

### ISSUE THREAD

**Issue by philipbl** [caedm/wall-ink-server#49]
If a reservation has an ampersand, it gets displayed as `&amp;`. I'm not sure if this is a bug with the wall-ink-server or reservation system. See attached picture for an example.

![img_4255](https://user-images.githubusercontent.com/1527647/50841048-180f1180-1321-11e9-8ee9-5fba6f3c3147.jpeg)

**Comment by jdeananderson** [comment]
Thank you for reporting the issue.  This was fixed in commit 049a20c51e17cc127ed4ee915b03b4cb9f16cef7 back on December 7th.  Our production systems on campus are running on code from September 2018, but we plan on updating everything starting in a week or so.  The latest version of the server requires a firmware update, so we will be rolling out a new production server and start with 6-8 screens pointed to it, and then converting over another 6-8 screens a week until it is finished.  We appreciate the feedback.  --Dean

**Comment by philipbl** [comment]
Great!
