### ISSUE TITLE
Server works with wrong DOCUMENT_ROOT

### ISSUE THREAD

**Issue by b3z** [caedm/wall-ink-server#73]
Hello, I am experiencing some strange issue.

The booked.php somehow works with a wrong document root:
Debug in browser:
```
Warning: require_once(/var/www/html/booked/Web/plugin_dependencies/iPlugin.php): failed to open stream: No such file or directory in /var/www/html/booked/Web/wall-ink/plugins/booked.php on line 2

Fatal error: require_once(): Failed opening required '/var/www/html/booked/Web/plugin_dependencies/iPlugin.php' (include_path='.:/usr/share/php') in /var/www/html/booked/Web/wall-ink/plugins/booked.php on line 2
```

Content of booked.php line 1-2
```bash
pi@banana-server:~/wall-ink-server$ cat /var/www/html/booked/Web/wall-ink/plugins/booked.php
<?php
require_once("$_SERVER[DOCUMENT_ROOT]/plugin_dependencies/iPlugin.php");
```

Anyone an idea how to fix that and make the document root be with the wall-ink part in the url with those being my settings:

```cfg
# ****************************************
# ******  Wall-ink-server settings  ******
# ****************************************
buildTimeWebDirectory="/home/pi/wall-ink-server"
runTimeWebDirectory="/var/www/html/booked/Web/wall-ink"
```

**Comment by AndersenJ** [comment]
Trying to figure out what the best way to fix this is. If I'm reading this right, we need to replace every instance of `$_SERVER[DOCUMENT_ROOT]` with `$config->runTimeWebDirectory` instead. The problem is, there needs to be some way to source the config file, which also relies on `$_SERVER[DOCUMENT_ROOT]`. You could hardcode it, but that would only solve the problem for you. I might just fix it so the makefile inserts the correct line into the file at build-time. I don't really like that solution, but no better solution is occurring to me right now.

**Comment by AndersenJ** [comment]
On second thought, I could probably just use relative paths for this.

**Comment by AndersenJ** [comment]
Anyways, I found a solution that is kind of like relative paths, but isn't actually relative paths because those are [fundamentally broken](https://yagudaev.com/posts/resolving-php-relative-path-problem/) in PHP (in my opinion). It seems like this particular bug is pretty common throughout the project, but I hope to have a fix on the development branch sometime today or tomorrow.

**Comment by AndersenJ** [comment]
@b3z Could you try the latest commit on the development branch?

**Comment by b3z** [comment]
Issue is fixed, works now for me with the latest commit on the development branch.
